# Report structure
:trello_sources:
  :epics:
    board_ose_roadmap:
      :board_id: "5307a94953d330a60f9e8f00"
      :lists: 
        :epic_backlog: "5307a94953d330a60f9e8f02"
#        :done_3_1: "563f99cc32e714b87f661718"
#        :done_3_0: "5307a94953d330a60f9e8f03"
#        :done_2_x: "555e1ab2cb317ecec171718b"
  :assignments:
    board_e2e:
      :board_id: "5640b810860935a27a6139d6"
      :lists:
        :backlog: "5640bb2965cec07628642994"
        :next: "5640bb2ac2110e0628dde44a"
        :in_progress: "5640bb2c9826d99d92fbfd7b"
:transform:
  :tags:
    funding_buckets:
      :tag_prefix: "fb_"
      :pretty_name: "Funding Bucket"
    project:
      :tag_prefix: "project_"
      :pretty_name: "Project"
    team:
      :tag_prefix: "team_"
      :pretty_name: "Team"
  :add_for_board: #map all board's items to specific project
    AOS:
      :project: "AOS E2E"
      :team: "ContainerILT"
      :board_id: "5640b810860935a27a6139d6"
:output_metadata:
  :template_id: "1uaO6Kepx8sbF2RuKq3LClxEAqZIWs_4lHwiDPwq4R5Q" #Google spreadsheet template to use for the report
  :report_name: "OSE Epics-Assignments Report "
  :columns:
    1:
      :name: "Assignment ID"
      :key: ":id"
    2:
      :name: "Assignment"
      :key: ":name"
    3:
      :name: "Owner"
      :key: ":members"
    4:
      :name: "Project"
      :key: ":project"
    5:
      :name: "Funding Buckets"
      :key: ":funding_buckets"
    6:
      :name: "Status"
      :key: ":status"
    7:
      :name: "Last Updated"
      :key: ":last_updated"
    8:
      :name: "Detailed Status"
      :key: ":detailed_status"
    9:
      :name: "Tags"
      :key: ":tags"
    10:
      :name: "Short URL"
      :key: ":short_url"
    11:
      :name: "Board"
      :key: ":board_name"
    12:
      :name: "List"
      :key: ":list_name"
    13:
      :name: "Team"
      :key: ":team"
    14:
      :name: "Type"
      :key: ":card_type"
    15:
      :name: "Last Moved"
      :key: ":latest_move"
    16:
      :name: "Due Date"
      :key: ":due_date"
    17:
      :name: "Epic Label"
      :key: ":epic"
    18:
      :name: "Labels"
      :key: ":labels"
    19:
      :name: "Epic"
      :key: ":epic_friendly"
    20:
      :name: "User ID"
      :key: ":user_id"
