# Report structure
:trello_sources:
  :assignments:
    board_syseng:
      :board_id: "55b8e03be0b7b68131139cf1"
      :lists: 
        in_progress: "55b8e064fb3f1d621db0746f"
        unsorted_backlog: "55b8e05ebda5066e15c24025"
        approved_backlog: "569ebdafc1fff35207ce2a86"
        investigation: "55b8e83c1df82cf0bbd4edba"
        internal: "569ebd9003675b8ce49862a9"
        unicorns: "569ebde429fc6b3d5e8495b9"
      :done_lists:
        completed: "55b8e4428ec04b31597cd5c3"
    board_e2e:
      :board_id: "5640b810860935a27a6139d6"
      :lists:
        backlog: "5640bb2965cec07628642994"
        next: "5640bb2ac2110e0628dde44a"
        in_progress: "5640bb2c9826d99d92fbfd7b"
  :epics:
    board_e2e:
      :board_id: "5640b810860935a27a6139d6"
      :lists:
        :features: "565f025438b850e2051e6974"
:transform:
  :tags:
    funding_buckets:
      :tag_prefix: "fb_"
      :pretty_name: "Funding Bucket"
    project:
      :tag_prefix: "project_"
      :pretty_name: "Project"
    sponsor:
      :tag_prefix: "sponsor_"
      :pretty_name: "Sponsor"
    epic:
      :tag_prefix: "epic_"
      :pretty_name: "Epic tag"
  :add_for_board: #map all board's items to specific project
    AOS:
      :project: "AOS E2E"
      :team: "ContainerILT"
      :board_id: "5640b810860935a27a6139d6"
  :sprint_list: #The list used for sprints. Sprint properties are taken from the card in this list named 'Sprint XXX'
    board_e2e:
      :board_id: "5640b810860935a27a6139d6"
      :list_id: "5640bb2c9826d99d92fbfd7b"
:output_metadata:
  :template_id: "1wqVXoPnBxD7HI8HHyHtlrdp0Z0Ij2krmHpln-IJscT0" #Google spreadsheet template to use for the report
  :report_name: "SysEng Assignments Report "
  :columns:
    1:
      :name: "Assignment ID"
      :key: ":id"
    2:
      :name: "Assignment"
      :key: ":name"
    3:
      :name: "Owner"
      :key: ":members"
    4:
      :name: "Project"
      :key: ":project"
    5:
      :name: "Status Updated by"
      :key: ":status_by"
    6:
      :name: "Status"
      :key: ":status"
    7:
      :name: "Last Updated"
      :key: ":status_comment_date"
    8:
      :name: "Detailed Status"
      :key: ":status_comment"
    9:
      :name: "Tags"
      :key: ":tags"
    10:
      :name: "Short URL"
      :key: ":short_url"
    11:
      :name: "Board"
      :key: ":board_name"
    12:
      :name: "List"
      :key: ":list_name"
    13:
      :name: "Type"
      :key: ":card_type"
    14:
      :name: "Last Moved"
      :key: ":latest_move"
    15:
      :name: "Due Date"
      :key: ":due_date"
    16:
      :name: "Epic tag"
      :key: ":epic"
    17:
      :name: "Labels"
      :key: ":labels"
    18:
      :name: "Epic"
      :key: ":epic_friendly"
    19:
      :name: "User ID"
      :key: ":user_id"
    20:
      :name: "Sponsor"
      :key: ":sponsor"
    21:
      :name: "Completed Date"
      :key: ":completed_date"
